### ISSUE TITLE
`<null>` gets removed from Tact type errors

### ISSUE THREAD

**Issue by anton-trunov** [nujan-io/nujan-ide#98]
```tact
contract Test {

  get fun cmp(): Bool {
    let x: Int = 42;
    return x == null;  // type error
  }
}
```

Here is the error message from Tact CLI:
```shell
💼 Compiling project test ...
Tact compilation failed
Error: test.tact:5:12: Incompatible types "Int" and "<null>" for binary operator "=="
Line 5, col 12:
  4 |     let x: Int = 42;
> 5 |     return x == null;
                 ^~~~~~~~~
  6 |   }

    at throwCompilationError (/Users/anton_1/ton/tact/dist/errors.js:77:11)
    at resolveBinaryOp (/Users/anton_1/ton/tact/dist/types/resolveExpression.js:158:56)
    at resolveExpression (/Users/anton_1/ton/tact/dist/types/resolveExpression.js:465:20)
    at processStatements (/Users/anton_1/ton/tact/dist/types/resolveStatements.js:274:73)
    at processFunctionBody (/Users/anton_1/ton/tact/dist/types/resolveStatements.js:443:17)
    at resolveStatements (/Users/anton_1/ton/tact/dist/types/resolveStatements.js:561:23)
    at precompile (/Users/anton_1/ton/tact/dist/pipeline/precompile.js:24:53)
    at build (/Users/anton_1/ton/tact/dist/pipeline/build.js:62:43)
    at Object.run (/Users/anton_1/ton/tact/dist/node.js:100:47)
```

But Web IDE shows the following:

```
main.tact:6:12: Incompatible types "Int" and "" for binary operator "==" 
Line 6, col 12: 
  5 |     let x: Int = 42; 
> 6 |     return x == null; 
                 ^~~~~~~~~ 
  7 |   } 
```

**Comment by rahulyadav-57** [comment]
I'm using a helper function to parse HTML, which then converts it to ANSI. It appears that `<null>` is mistakenly identified as an HTML tag and gets removed in this process. I'll fix it.
